export const AUTH_REQUEST: string = 'AUTH_REQUEST';
export type AUTH_REQUEST = typeof AUTH_REQUEST;

export const AUTH_REQUEST_SUCCESS: string = 'AUTH_REQUEST_SUCCESS';
export type AUTH_REQUEST_SUCCESS = typeof AUTH_REQUEST_SUCCESS;

export const AUTH_REQUEST_FAILED: string = 'AUTH_REQUEST_FAILED';
export type AUTH_REQUEST_FAILED = typeof AUTH_REQUEST_FAILED;

export default {
  AUTH_REQUEST,
  AUTH_REQUEST_FAILED,
  AUTH_REQUEST_SUCCESS,
};
